SELECT
PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY amount) AS q1,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY amount) AS median,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY amount) AS q3,
PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY amount) AS p90
FROM transactions;